name: Deploy
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build, tag, and push docker image to Amazon ECR
        run: |
          python --version
          python3 --version
          jq --version
