name: Docker Image CI

on:
  push:
jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3
    - name: set env
      run: |
        export TF_VAR_nr_license_key=NEW_RELIC_LICENSE
        export TF_VAR_google_client_id=GOOGLE_CLIENT_ID
    - name: get env
      run: |
        env
