name: Docker Image CI

on:
  push:
    branches: [dev, test ]
  pull_request:
    branches: [dev, test ]

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v2
    - name: preparation dev
      id: prep
      run: |
        ls
        pwd
        echo $CONDA
        echo $COMMON_SECRET > file.txt
        cat file.txt
        cat README.md
        ls
    - name: another time dev
      run: |
        echo $COMMON_SECRET
        echo $COMMON_SECRET > file2.txt
        cat file2.txt
  test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v2
    - name: preparation test
      id: prep
      run: |
        echo $COMMON_SECRET
        echo $COMMON_SECRET > file.txt
        cat file.txt
    - name: another time test
      run: |
        echo $COMMON_SECRET
        echo $COMMON_SECRET > file2.txt
        cat file2.txt
